"""Set the version everywhere from one place.

    python scripts/set_version.py 0.2.0

`pentimento/version.py` is the single source. This rewrites it, then
regenerates the two files that cannot read Python at build time: the
Windows version resource and the installer's include. `pyproject.toml`
reads the attribute directly, so it needs nothing.

CI verifies that a release tag matches this value rather than stamping it,
so the repository always records what was actually shipped.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = ROOT / "src" / "pentimento" / "version.py"
ISS_INCLUDE = ROOT / "desktop" / "version.iss"

SEMVER = re.compile(r"^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$")


def current() -> str:
    match = re.search(r'^__version__ = "([^"]+)"', VERSION_FILE.read_text(encoding="utf-8"),
                      re.MULTILINE)
    if match is None:
        raise SystemExit("could not find __version__")
    return match.group(1)


def regenerate(version: str, into: Path | None = None) -> tuple[Path, Path]:
    """Write the generated build inputs.

    `into` exists so a check can regenerate somewhere harmless and compare.
    An earlier version of that test wrote over the real files, which
    quietly repaired the drift it was supposed to report.
    """
    target = Path(into) if into else ISS_INCLUDE.parent
    target.mkdir(parents=True, exist_ok=True)

    iss = target / ISS_INCLUDE.name
    iss.write_text(
        "; Generated by scripts/set_version.py - do not edit.\n"
        f'#define AppVersion    "{version}"\n',
        encoding="utf-8",
    )

    if str(ROOT) not in sys.path:
        sys.path[:0] = [str(ROOT), str(ROOT / "src")]
    from desktop.version_info import build as build_resource

    resource = build_resource(target / "version_info.txt")
    return iss, resource


def set_version(version: str) -> None:
    if not SEMVER.match(version):
        raise SystemExit(f"not a semantic version: {version}")
    text = VERSION_FILE.read_text(encoding="utf-8")
    text = re.sub(r'^__version__ = "[^"]+"',
                  f'__version__ = "{version}"', text, count=1, flags=re.MULTILINE)
    VERSION_FILE.write_text(text, encoding="utf-8")
    regenerate(version)
    print(f"version set to {version}")
    print("remember to add a CHANGELOG entry before tagging")


if __name__ == "__main__":
    if len(sys.argv) == 1:
        print(current())
    elif sys.argv[1] == "--regenerate":
        regenerate(current())
        print(f"regenerated build files for {current()}")
    else:
        set_version(sys.argv[1])
