"""Generate the Windows version resource for the executable.

Without this the binary has no FileVersion, CompanyName or ProductName:
the Properties dialog is blank, Task Manager shows nothing useful, and an
Intune detection rule based on file version has nothing to match. It also
makes the file look anonymous to anything inspecting what is running,
which is the opposite of what an unsigned application wants.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path[:0] = [str(ROOT / "src")]

from pentimento.version import __version__  # noqa: E402

COMPANY = "Bebop.systems"
PRODUCT = "Pentimento"
DESCRIPTION = "Pentimento {version} - photo metadata, locally"
COPYRIGHT = "Copyright (c) 2026 Bebop.systems. MIT licence."

TEMPLATE = '''# Generated by desktop/version_info.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, 0),
    prodvers=({major}, {minor}, {patch}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        "040904B0",
        [
          StringStruct("CompanyName", "{company}"),
          StringStruct("FileDescription", "{description}"),
          StringStruct("FileVersion", "{version}"),
          StringStruct("InternalName", "{product}"),
          StringStruct("LegalCopyright", "{copyright}"),
          StringStruct("OriginalFilename", "{product}.exe"),
          StringStruct("ProductName", "{product}"),
          StringStruct("ProductVersion", "{version}"),
        ],
      )
    ]),
    VarFileInfo([VarStruct("Translation", [1033, 1200])]),
  ],
)
'''


def build(destination: Path | None = None) -> Path:
    destination = destination or (Path(__file__).resolve().parent / "version_info.txt")
    parts = (__version__.split("+")[0].split("-")[0].split("."))
    major, minor, patch = (int(parts[i]) if i < len(parts) else 0 for i in range(3))
    destination.write_text(
        TEMPLATE.format(
            major=major, minor=minor, patch=patch,
            version=__version__, company=COMPANY, product=PRODUCT,
            description=DESCRIPTION.format(version=__version__),
            copyright=COPYRIGHT,
        ),
        encoding="utf-8",
    )
    return destination


if __name__ == "__main__":
    written = build()
    print(f"{written}  ({written.stat().st_size} bytes)")
